package com.taskflow;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.AfterEach; // Adicione para limpar após cada teste
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.TestPropertySource;
import org.junit.jupiter.api.TestInstance; // Adicione esta importação
import org.junit.jupiter.api.TestInstance.Lifecycle; // Adicione esta importação

// Altera o ciclo de vida para permitir @BeforeAll não estático (mais idiomático no JUnit 5 com Spring)
@TestInstance(Lifecycle.PER_CLASS)
@ActiveProfiles("test")
@TestPropertySource(properties = {"spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration"})
public abstract class BaseIntegrationTest {

    @Autowired
    protected JdbcTemplate jdbcTemplate; // Injetar o template como campo

    private final String schemaSql = "DROP TABLE IF EXISTS projects, usuarios CASCADE;\n" + // Use CASCADE para segurança
            "CREATE TABLE usuarios (\n" +
            "    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
            "    name VARCHAR(255),\n" +
            "    email VARCHAR(255),\n" +
            "    password_hash VARCHAR(255),\n" +
            "    role VARCHAR(255)\n" +
            ");\n\n" +
            "CREATE TABLE projects (\n" +
            "    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
            "    name VARCHAR(255) NOT NULL,\n" +
            "    description TEXT,\n" +
            "    owner_id BIGINT NOT NULL,\n" +
            "    created_at TIMESTAMP NOT NULL,\n" +
            "    FOREIGN KEY (owner_id) REFERENCES usuarios(id)\n" +
            ");";

    // O @BeforeAll agora não é estático (graças ao @TestInstance)
    @BeforeAll
    void setupDatabaseSchema() {
        if (jdbcTemplate != null) {
            System.out.println("Configurando o esquema do banco de dados para testes...");
            jdbcTemplate.execute(schemaSql);
        } else {
            // Esta mensagem indica um erro de configuração do Spring
            System.err.println("ERRO: JdbcTemplate não injetado. Verifique a exclusão de auto-configurações.");
        }
    }

    // Boa prática: limpar dados após cada teste para garantir isolamento
    @AfterEach
    void cleanUp() {
        if (jdbcTemplate != null) {
            // Limpa apenas os dados, não o esquema, após cada teste
            jdbcTemplate.execute("DELETE FROM projects; DELETE FROM usuarios;");
        }
    }
}